modLoader = "javafml"
loaderVersion = "[1,)"
license = "LGPL-2.1-only"

[[mods]]
modId = "sableprotect"
version = "0.1.1"
displayName = "Sable Protect"
description = '''
Protection commands for Sable airships on NeoForge 1.21.1.
'''

[[dependencies.sableprotect]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sableprotect]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.sableprotect]]
modId = "sable"
type = "required"
versionRange = "[1.1.3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.sableprotect]]
modId = "simulated"
type = "required"
versionRange = "[0.0.1,)"
ordering = "AFTER"
side = "BOTH"
